### ISSUE TITLE
InvalidArgumentException: Magic request methods require a URI and optional options array

### ISSUE THREAD

**Issue by frankdors** [discovery-tecnologia/dsc-mercado-livre#79]
Estava usando no composer como "2.*", ao atualizar composer update começou a apresentar este erro:
`InvalidArgumentException: Magic request methods require a URI and optional options array`

Lib atualizou da **2.0.3-rc** para a **2.2.0-rc**

Configurei meu composer para utilizar a versão:

-  **2.0.3-rc** = OK ✅
-  **2.0.4-rc** = OK ✅
-  **2.1.0-rc** = Falha❌
-  **2.2.0-rc** = Falha ❌

Pelo que entendi tem algum problema que ocorre no **getMeli** desta nova implementação

Stack trace:
```#0 /var/www/html/sistema/vendor/dsc/mercado-livre/src/Handler/OAuth2ClientHandler.php(62): GuzzleHttp\Client->__call('getMeli', Array)
#1 /var/www/html/sistema/vendor/dsc/mercado-livre/src/Handler/OAuth2ClientHandler.php(49): Dsc\MercadoLivre\Handler\OAuth2ClientHandler->authorize(Object(GuzzleHttp\Psr7\Request))
#2 /var/www/html/sistema/vendor/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php(66): Dsc\MercadoLivre\Handler\OAuth2ClientHandler->Dsc\MercadoLivre\Handler\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#3 /var/www/html/sistema/vendor/guzzlehttp/guzzle/src/Middleware.php(29): GuzzleHttp\PrepareBodyMiddleware->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#4 /var/www/html/sistema/vendor/guzzlehttp/guzzle/src/RedirectMiddleware.php(70): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#5 /var/www/html/sistema/vendor/guzzlehttp/guzzle/src/Middleware.php(59): GuzzleHttp\RedirectMiddleware->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#6 /var/www/html/sistema/vendor/guzzlehttp/guzzle/src/HandlerStack.php(71): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#7 /var/www/html/sistema/vendor/guzzlehttp/guzzle/src/Client.php(351): GuzzleHttp\HandlerStack->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#8 /var/www/html/sistema/vendor/guzzlehttp/guzzle/src/Client.php(162): GuzzleHttp\Client->transfer(Object(GuzzleHttp\Psr7\Request), Array)
#9 /var/www/html/sistema/vendor/guzzlehttp/guzzle/src/Client.php(182): GuzzleHttp\Client->requestAsync('POST', Object(GuzzleHttp\Psr7\Uri), Array)
#10 /var/www/html/sistema/vendor/dsc/mercado-livre/src/Client.php(115): GuzzleHttp\Client->request('POST', '/items', Array)
#11 /var/www/html/sistema/vendor/dsc/mercado-livre/src/Client.php(71): Dsc\MercadoLivre\Client->execute('POST', '/items', Array)
#12 /var/www/html/sistema/vendor/dsc/mercado-livre/src/BaseService.php(64): Dsc\MercadoLivre\Client->post('/items', '{"title":"Chama...', Array)
#13 /var/www/html/sistema/vendor/dsc/mercado-livre/src/Announcement.php(25): Dsc\MercadoLivre\BaseService->post('/items', Object(Dsc\MercadoLivre\Announcement\Item))
#14 /var/www/html/sistema/action/integracoes/mercadolivreanuncio.php(537): Dsc\MercadoLivre\Announcement->create(Object(Dsc\MercadoLivre\Announcement\Item))
#15 /var/www/html/sistema/page/produto.php(694): Action\Integracoes\MercadoLivreAnuncio->anunciar()
```

**Comment by dilowagner** [comment]
@frankdors 
Obrigado por reportar!
Qual a versao do PHP vc esta usando?

**Comment by dilowagner** [comment]
Poutz, encontrei o problema @frankdors 
Foi caca minha mesmo hehe... vou gerar uma versao com a correcao.

Os testes nao pegaram :-1: 

Valeu

**Comment by dilowagner** [comment]
@frankdors 
[Versao 2.2.1-rc](https://github.com/discovery-tecnologia/dsc-mercado-livre/releases/tag/2.2.1-rc)

Valeu mais uma vez :+1:
